<?php
/**
 * Description of ErrorCode.php
 * @copyright Copyright (c) DOTSPLATFORM, LLC
 * @author    Bogdan Mamontov <bohdan.mamontov@dotsplatform.com>
 */

namespace Dots\WoltDrive\Client\Resources\Consts;

enum ErrorCode: string
{
    case SHIPMENT_PROMISE_NOT_FOUND = 'SHIPMENT_PROMISE_NOT_FOUND';
    case DROPOFF_OUTSIDE_OF_DELIVERY_AREA = 'DROPOFF_OUTSIDE_OF_DELIVERY_AREA';
    case PICKUP_OUTSIDE_DELIVERY_AREA = 'PICKUP_OUTSIDE_DELIVERY_AREA';
    case INVALID_DROPOFF_ADDRESS = 'INVALID_DROPOFF_ADDRESS';
    case INVALID_PICKUP_ADDRESS = 'INVALID_PICKUP_ADDRESS';
    case INVALID_PAYLOAD = 'INVALID_PAYLOAD';
    case REQUEST_OUTSIDE_DELIVERY_HOURS = 'REQUEST_OUTSIDE_DELIVERY_HOURS';
    case INVALID_SCHEDULED_DROPOFF_TIME = 'INVALID_SCHEDULED_DROPOFF_TIME';
    case CASH_ON_DELIVERY_DISABLED = 'CASH_ON_DELIVERY_DISABLED';
    case DELIVERY_NOT_ENABLED_FOR_DELIVERY_AREA = 'DELIVERY_NOT_ENABLED_FOR_DELIVERY_AREA';
    case DELIVERY_AREA_CLOSED = 'DELIVERY_AREA_CLOSED';
    case DELIVERY_AREA_CLOSED_TEMPORARILY = 'DELIVERY_AREA_CLOSED_TEMPORARILY';
    case DUPLICATE_ORDER = 'DUPLICATE_ORDER';
    case VENUE_CLOSED = 'VENUE_CLOSED';
    case MISSING_MERCHANT_CONFIGURATION = 'MISSING_MERCHANT_CONFIGURATION';
    case B2B_CONFIG_NOT_FOUND = 'B2B_CONFIG_NOT_FOUND';
    case CORPORATE_PAYMENT_METHOD_NOT_FOUND = 'CORPORATE_PAYMENT_METHOD_NOT_FOUND';
    case DELIVERY_CONFIG_MISSING_PRICING = 'DELIVERY_CONFIG_MISSING_PRICING';
    case DELIVERY_CONFIG_DELIVERY_NOT_ENABLED = 'DELIVERY_CONFIG_DELIVERY_NOT_ENABLED';
    case VENUE_ORDER_LIMIT_EXCEEDED = 'VENUE_ORDER_LIMIT_EXCEEDED';
    case ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
    case GENERIC_INTERNAL_ERROR = 'GENERIC_INTERNAL_ERROR';
    case INVALID_ORDER_STATE_TRANSITION = 'INVALID_ORDER_STATE_TRANSITION';
}
